version: '3.8'

services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: orders-api
    container_name: orders-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  mysql:
    image: mysql:8.0
    container_name: orders-api-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 5555:3306
  nginx:
    image: nginx:alpine
    container_name: orders-api-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/

  redis:
    image: redis:latest
    container_name: orders-api-redis
    ports:
      - "6379:6379"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
